#enter your aws consoles credentials and change variables according to you
---
- hosts: localhost
  tasks:
          - rds:
                  aws_access_key: ####################
                  aws_secret_key: ####################
                  command: create
                  instance_name: new-database
                  region: us-east-1
                  #vpc_security_groups: sg-0796d226cec08f600
                  #subnet: vpc-0debe62c4a8ebeebb
                  db_engine: MySQL
                  db_name: trial101
                  size: 1000
                  instance_type: db.m5.xlarge
                  username: mysql_admin
                  password: 1nsecure
                  tags:
                          Environment: testing
                          Application: cms

